plugins {
	id "com.crystaelix.loom" version "1.17-SNAPSHOT"
	id "eclipse"
	id "idea"
	id "maven-publish"
	id "com.crystaelix.blossom" version "1.3.2"
	id "me.modmuss50.mod-publish-plugin" version "2.2.0"
}

repositories {
	mavenCentral()
	flatDir {
		dirs "libs"
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.parchmentmc.net/"
			}
		}
		filter {
			includeGroup "org.parchmentmc.data"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.blamejared.com/"
			}
		}
		filter {
			includeGroup "net.mezzdev.config"
			includeGroup "mezz.jei"
			includeGroup "foundry.veil"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.ithundxr.dev/snapshots/"
			}
		}
		filter {
			includeGroup "com.tterrag.registrate"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.createmod.net/"
			}
		}
		filter {
			includeGroup "dev.engine-room.flywheel"
			includeGroup "net.createmod.ponder"
			includeGroup "com.simibubi.create"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.ryanhcode.dev/releases/"
			}
		}
		filter {
			includeGroup "dev.ryanhcode.sable-companion"
			includeGroup "dev.ryanhcode.sable"
			includeGroup "dev.simulated_team.simulated"
			includeGroup "dev.eriksonn.aeronautics"
			includeGroup "dev.ryanhcode.offroad"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.squiddev.cc/"
			}
		}
		filter {
			includeGroup "cc.tweaked"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://thedarkcolour.github.io/KotlinForForge/"
			}
		}
		filter {
			includeGroup "thedarkcolour"
		}
	}
	exclusiveContent {
		forRepository {
			ivy {
				// Hacky ivy pattern to get railx into development environment
				artifactPattern "https://github.com/lhwdev/[module]/releases/download/([classifier]-)[revision]/[module]-[revision].jar"
				metadataSources {
					artifact()
				}
			}
		}
		filter {
			includeGroup "com.lhwdev.minecraft"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.realrobotix.me/master/"
			}
		}
		filter {
			includeGroup "com.copycatsplus"
			includeGroup "com.rbasamoyai"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.firstdarkdev.xyz/snapshots/"
			}
		}
		filter {
			includeGroup "com.lowdragmc.ldlib2"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://cursemaven.com/"
			}
		}
		filter {
			includeGroup "curse.maven"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://api.modrinth.com/maven/"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://jitpack.io/"
			}
		}
		filter {
			includeModule("com.github.misterblusky9", "pocket")
		}
	}
}

def mcVersion = "1.21.1"
def modName = "simurail"
def modId = "simurail"
def specVersion = "0"
def vendor = "thelm"
group = "com.crystaelix"
def baseVersion = "0.1.0"

version = hasProperty("commitHash") ? "${baseVersion}+mc${mcVersion}+${commitHash}" : "${baseVersion}+mc${mcVersion}"

def archivesName = "${modName}"
base.archivesName = archivesName

sourceSets {
	main
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
		vendor = JvmVendorSpec.AZUL
	}
	withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
}

loom {
	silentMojangMappingsLicense()
	runs {
		configureEach {
			property "forge.logging.console.level", "debug"
		}
		client
		server
	}
}

dependencies {
	// Minecraft
	minecraft "com.mojang:minecraft:1.21.1"
	mappings loom.layered {
		officialMojangMappings()
		parchment "org.parchmentmc.data:parchment-1.21.1:2024.11.17@zip"
	}
	neoForge "net.neoforged:neoforge:21.1.249"

	// Dependencies
	implementation("mezz.jei:jei-1.21.1-neoforge:19.44.0.405") {transitive = false}
	//implementation("net.mezzdev.config:mezz_config-1.21.1-neoforge:0.6.7") {transitive = false}
	//implementation("mezz.jei:jei-1.21.1-neoforge:19.57.0.450") {transitive = false}
	implementation "com.tterrag.registrate:Registrate:MC1.21-1.3.0+67"
	implementation "dev.engine-room.flywheel:flywheel-neoforge-1.21.1:1.0.6-41"
	implementation "net.createmod.ponder:ponder-neoforge:1.0.82+mc1.21.1"
	implementation("com.simibubi.create:create-1.21.1:6.0.10-280:slim") {transitive = false}
	implementation("foundry.veil:veil-neoforge-1.21.1:4.1.4") {transitive = false}
	implementation "dev.ryanhcode.sable-companion:sable-companion-common-1.21.1:1.6.0"
	implementation("dev.ryanhcode.sable:sable-neoforge-1.21.1:2.0.6") {transitive = false}
	implementation("dev.simulated_team.simulated:simulated-neoforge-1.21.1:1.3.1") {transitive = false}

	// Performance
	runtimeOnly "curse.maven:yeetusexperimentus-635427:5444189"
	runtimeOnly "curse.maven:modernfix-790626:8774737"
	runtimeOnly "curse.maven:ferritecore-429235:7524151"

	// Leave mods out with -PwithoutMods=all, -PwithoutMods=electroenergetics,railways
	def compat = ["compileOnly", "runtimeOnly"]
	def extra = ["runtimeOnly"]
	def mods = [
		// Compat
		computercraft     : [configurations: compat, notation: "cc.tweaked:cc-tweaked-1.21.1-forge:1.120.2"],
		electroenergetics : [configurations: compat, notation: "curse.maven:create-electro-energetics-1443327:8974177"],
		create_bb         : [configurations: compat, notation: "curse.maven:create-blocks-bogies-1317252:8723463"],
		railways          : [configurations: compat, notation: "curse.maven:steam-n-rails-neoforge-1414670:8522154"],
		kotlinforforge    : [configurations: compat, notation: "thedarkcolour:kotlinforforge-neoforge:5.12.0"],
		railx             : [configurations: compat, notation: "com.lhwdev.minecraft:railx:0.2.0-build.15:mc1.21.1", dependsOn: ["kotlinforforge", "railways"]],
		offroad           : [configurations: compat, notation: "dev.ryanhcode.offroad:offroad-neoforge-1.21.1:1.3.1", transitive: false],
		copycats          : [configurations: compat, notation: "com.copycatsplus:copycats:3.0.8+mc.1.21.1-neoforge", transitive: false],

		// Testing
		aeronautics           : [configurations: extra, notation: "dev.eriksonn.aeronautics:aeronautics-neoforge-1.21.1:1.3.1", transitive: false],
		ritchiesprojectilelib : [configurations: extra, notation: "com.rbasamoyai:ritchiesprojectilelib:2.1.2+mc.1.21.1-neoforge"],
		createbigcannons      : [configurations: extra, notation: "com.rbasamoyai:createbigcannons:5.11.7+mc.1.21.1", transitive: false, dependsOn: ["ritchiesprojectilelib"]],
		transmission_linkage  : [configurations: extra, notation: "curse.maven:create-aeronautics-transmission-linkage-1548056:8790451"],
		drive_by_wire         : [configurations: extra, notation: "curse.maven:drive-by-sable-1576519:8996636"],
		aeronautics_toolgun   : [configurations: extra, notation: "curse.maven:create-aeronauticstoolgun-1521349:8701394"],
		create_coasters       : [configurations: extra, notation: "curse.maven:create-coasters-simulated-1601871:8655742"],
		ldlib2                : [configurations: extra, notation: "com.lowdragmc.ldlib2:ldlib2-neoforge-1.21.1:2.2.37:all", transitive: false],
		schematic_tool        : [configurations: extra, notation: "curse.maven:sable-schematic-tool-1526951:8606655", dependsOn: ["ldlib2"]],
		synaxis               : [configurations: extra, notation: "curse.maven:synaxis-1526348:8606652", dependsOn: ["ldlib2", "schematic_tool"]],
		//pocket                : [configurations: extra, notation: "curse.maven:create-pocket-sized-1672138:9001968"],
	]

	def withoutMods = (findProperty("withoutMods") ?: "").toString().split(",")*.trim() - ""
	def disabledMods = (withoutMods.contains("all") ? mods.keySet().toList() : withoutMods.findAll { it in mods })
	def disabledMoreMods = true
	while(disabledMoreMods) {
		disabledMoreMods = false
		mods.each { id, mod ->
			if(!disabledMods.contains(id) && mod.dependsOn.any { it in disabledMods }) {
				disabledMods.add(id)
				disabledMoreMods = true
			}
		}
	}

	mods.each { id, mod ->
		mod.configurations.each {
			if(it != "runtimeOnly" || id !in disabledMods) {
				add(it, mod.notation) { it.transitive = mod.getOrDefault("transitive", true) }
			}
		}
	}
}

def replacements = [
	"0@VERSION@": version
]

blossom {
	replaceToken(replacements)
}

processResources {
	inputs.properties(replacements)
	filesMatching(["mcmod.info", "META-INF/mods.toml", "META-INF/neoforge.mods.toml", "fabric.mod.json"]) {
		filter {
			it.replace(replacements)
		}
	}
}

def manifestAttributes = [
	"Specification-Title": modName,
	"Specification-Vendor": vendor,
	"Specification-Version": specVersion,
	"Implementation-Title": archivesName,
	"Implementation-Version": version,
	"Implementation-Vendor": vendor
]

jar {
	manifest.attributes(manifestAttributes)
}

sourcesJar {
	manifest.attributes(manifestAttributes)
}

publishing {
	publications {
		register("mavenJava", MavenPublication) {
			artifactId = archivesName
			artifact remapJar
			artifact sourcesJar
		}
	}
	repositories {
		if(project.hasProperty("CrystaelixMavenUsername") && project.hasProperty("CrystaelixMavenPassword")) {
			maven {
				name = "CrystaelixMaven"
				url = "https://maven.crystaelix.com/releases/"
				credentials(PasswordCredentials)
			}
		}
	}
}

publishMods {
	file = remapJar.archiveFile
	version = displayName = project.version
	changelog = file("changelog.md").text
	type = BETA
	modLoaders.add("neoforge")
	additionalFiles.from(sourcesJar.archiveFile)

	curseforge {
		accessToken = providers.gradleProperty("curseforge.token")
		projectId = "1583981"
		minecraftVersions.add(mcVersion)
		client = true
		server = true
		requires "create-aeronautics"
	}

	modrinth {
		accessToken = providers.gradleProperty("modrinth.token")
		projectId = "Y1cfijof"
		minecraftVersions.add(mcVersion)
		environment = CLIENT_AND_SERVER
		requires "create-aeronautics"
	}
}
